title: Granxa de pitas García SA
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://garalbjoe.github.io/

nav_external_links:
  - title: Os millores ovos
    url: https://www.youtube.com/watch?app=desktop&v=BRvot4araGM
    hide icon: false
    opens_in_new_tab: true

<img src="https://img.mmcesim.org/logo/mmCEsim_logo_256.png" width="48">
<pre> </pre>
mmCEsim
