title: " "
logo: https://www.todopollo.es/wp-content/uploads/2020/11/huevos.jpg
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://garalbjoe.github.io/

nav_external_links:
  - title: Os millores ovos
    url: https://www.youtube.com/watch?app=desktop&v=BRvot4araGM
    hide icon: false
    opens_in_new_tab: true

